export const questions = [
    { question: "I think I have a particular meaning and purpose of my life.", answer: "strongly agree" },
    { question: "I have happy memories of the past.", answer: "undecided" },
    { question: "I am very much satisfied about everything in my life.", answer: "agree" },
    { question: "In general, I feel I am in charge of the situation in which I live.", answer: "strongly disagree" },
    { question: "In most ways my life is close to my ideal.", answer: "disagree" },
    { question: "The conditions of my life are excellent.", answer: "strongly agree" },
    { question: "So far, I have the important things I want in life.", answer: "undecided" },
    { question: "If I could live my life over, I would change almost nothing.", answer: "agree" },
    { question: "In many ways, I feel contented about my achievements in life.", answer: "strongly disagree" },
    { question: "I am living the kind of life I wanted to.", answer: "strongly agree" },
    { question: "I find easy to make decisions.", answer: "disagree" },
    { question: "In my daily life I get a chance to show how capable I am.", answer: "strongly disagree" },
    { question: "I feel positive and creative.", answer: "undecided" },
    { question: "I find I can think quite clearly.", answer: "agree" },
    { question: "I am quite good at managing responsibilities of my daily life.", answer: "strongly agree" },
    { question: "For me, life has been a continuous process of learning, changing, and growth.", answer: "disagree" },
    { question: "I feel that I am capable of working hard.", answer: "strongly agree" },
    { question: "I feel eager to tackle my daily tasks or make new decisions.", answer: "agree" },
    { question: "I feel I can easily handle or cope with any serious problem.", answer: "undecided" },
    { question: "I think it is important to have new experiences that challenge how you think about yourself and the world.", answer: "strongly disagree" },
    { question: "I take immense interest in other people.", answer: "agree" },
    { question: "I always keep committed and involved.", answer: "strongly agree" },
    { question: "I have an adjusting nature and sense of belongingness.", answer: "undecided" },
    { question: "I feel I must do what others expect me to do.", answer: "disagree" },
    { question: "People would describe me as a giving person, willing to share my time with others.", answer: "strongly agree" },
    { question: "I have a good influence on life.", answer: "strongly disagree" },
    { question: "It is always necessary that others approve of what I do.", answer: "undecided" },
    { question: "Maintaining close relationships gives pleasure to me.", answer: "disagree" },
    { question: "I experience warm and trusting relationships with others.", answer: "strongly agree" },
    { question: "I believe that people are essentially good and can be trusted.", answer: "strongly disagree" },
    { question: "I remain energetic, active, and vigorous the whole day.", answer: "agree" },
    { question: "The thought of an accident doesn't affect me.", answer: "undecided" },
    { question: "Tension in life doesn't affect my health.", answer: "strongly disagree" },
    { question: "I have no difficulty sleeping.", answer: "strongly agree" },
    { question: "I keep myself busy the whole day.", answer: "disagree" },
    { question: "Illness doesn't affect my mental health.", answer: "agree" },
    { question: "I feel rested when I wake up in the morning.", answer: "strongly disagree" },
    { question: "Talking or thinking about my illness doesn't make any difference to me.", answer: "undecided" },
    { question: "Usually, I don't feel tired, worn out, used up, or exhausted.", answer: "strongly agree" },
    { question: "Age-related problems are part of life.", answer: "strongly disagree" },
    { question: "Personal relationships give me pleasure.", answer: "undecided" },
    { question: "I enjoy the company of other people.", answer: "strongly agree" },
    { question: "I enjoy my personal achievements.", answer: "agree" },
    { question: "I perform useful activities like reading, gardening, etc., in my leisure time.", answer: "strongly disagree" },
    { question: "I have no hesitation in talking to anyone.", answer: "disagree" },
    { question: "I like to do any task at the right place and right time.", answer: "strongly agree" },
    { question: "I have good relations with relatives and friends.", answer: "disagree" },
    { question: "I feel satisfied by doing religious activities.", answer: "strongly agree" },
    { question: "I like to watch programs on TV with everyone.", answer: "undecided" },
    { question: "I am always careful about my manner of dress.", answer: "agree" }
];


